import express from "express";
import Database from "better-sqlite3";
import { GoogleGenAI } from "@google/genai";
import dotenv from "dotenv";
import path from "path";
import { fileURLToPath } from "url";

dotenv.config();
const __dirname = path.dirname(fileURLToPath(import.meta.url));
const app = express();
const port = Number(process.env.PORT || 3000);
const db = new Database(path.join(__dirname, "data", "plating.db"));

db.exec(`
CREATE TABLE IF NOT EXISTS chats (
 id INTEGER PRIMARY KEY AUTOINCREMENT,
 role TEXT NOT NULL,
 content TEXT NOT NULL,
 created_at TEXT DEFAULT CURRENT_TIMESTAMP
);
CREATE TABLE IF NOT EXISTS bath_checks (
 id INTEGER PRIMARY KEY AUTOINCREMENT,
 bath TEXT, volume REAL, ph REAL, temp REAL, amps REAL, area_dm2 REAL,
 ni_so4 REAL, ni_cl REAL, boric REAL, notes TEXT, result TEXT,
 created_at TEXT DEFAULT CURRENT_TIMESTAMP
);
`);

const knowledge = `
PLATING AI — SAFE BASELINE KNOWLEDGE
Scope: decorative nickel/chrome metal finishing. This baseline is not a substitute for the chemical supplier's technical data sheet, site SOP, industrial hygiene assessment, or competent plating engineer.

PROCESS:
1. Inspect and identify substrate/material.
2. Mechanical preparation/polishing.
3. Cleaning/degreasing.
4. Rinse.
5. Activation/pickling appropriate to substrate.
6. Rinse.
7. Undercoat where the site's process requires it.
8. Nickel plating.
9. Rinse.
10. Decorative chrome or other chrome system according to the bath supplier.
11. Rinse and neutralization/finishing as applicable.
12. Quality inspection.

NICKEL:
A Watts-type nickel bath commonly uses nickel sulfate, nickel chloride and boric acid, but the exact target values vary by chemistry and supplier. Do NOT invent a correction dose when the product grade, assay, bath volume and analytical result are unknown.
Important control variables: pH, temperature, current density, agitation, filtration, anode condition, chloride, boric acid, nickel metal, contamination, brightener/additive balance, contact resistance and pretreatment.

TROUBLESHOOTING:
Dull nickel can have multiple causes: low/high pH, temperature out of range, current density outside the bath's operating window, poor cleaning/activation, additive imbalance, contamination, poor filtration/agitation, anode problems, or electrical contact problems.
Burning can be associated with excessive local current density, poor racking/contact, inadequate solution movement, geometry, or bath imbalance.
Peeling/blistering often requires checking substrate preparation, activation, intercoat adhesion, contamination and current ramp/contact.
Dark or uneven chrome requires checking substrate/nickel condition, electrical distribution, bath chemistry, temperature, current density, anode/cathode arrangement and contamination.

CHROME SAFETY:
Chrome electroplating may involve hexavalent chromium (Cr(VI)). Cr(VI) is carcinogenic and can damage the respiratory system, skin, eyes, kidneys and liver. Mist can be generated by hydrogen bubbles and during loading/unloading or chemical additions. Use engineered local exhaust ventilation, appropriate PPE, hygiene and exposure controls. Never tell an operator to bypass ventilation or PPE. Do not give improvised Cr(VI) mixing instructions. Follow the site's SDS and supplier instructions.

DECISION POLICY:
- If critical data are missing, ask for the minimum missing data.
- Never claim a bath is "correct" merely from one parameter.
- Never fabricate chemical concentrations, supplier-specific additions, or safety limits.
- For exact dosing, require verified bath analysis + verified product concentration/assay + actual bath volume + supplier-approved correction formula.
- If Cr(VI) exposure, spill, splash, mist failure, or unknown chemical mixing is involved: stop the operation, isolate the hazard, follow the site's emergency/SDS procedure and escalate to the responsible safety/technical person.
`;

function localAnalysis(body) {
  const { bath, volume, ph, temp, amps, area_dm2, ni_so4, ni_cl, boric, notes } = body;
  const warnings = [];
  const actions = [];
  const missing = [];
  if (!bath) missing.push("jenis bak");
  if (!(Number(volume) > 0)) missing.push("volume bak (L)");
  if (ph === "" || ph == null || !Number.isFinite(Number(ph))) missing.push("pH");
  if (temp === "" || temp == null || !Number.isFinite(Number(temp))) missing.push("temperatur");
  if (amps === "" || amps == null || !Number.isFinite(Number(amps))) missing.push("arus");
  if (area_dm2 === "" || area_dm2 == null || !Number.isFinite(Number(area_dm2))) missing.push("luas aktif (dm²)");

  if (bath === "chrome") {
    warnings.push("Bak chrome dapat melibatkan Cr(VI). Jangan melakukan koreksi chemical berdasarkan tebakan. Ikuti SDS, SOP lokasi, dan supplier.");
    actions.push("Pastikan LEV/ventilasi lokal aktif dan PPE sesuai sebelum operasi.");
    actions.push("Jika ada mist berlebih, tumpahan, atau paparan, hentikan pekerjaan dan ikuti prosedur darurat lokasi.");
  }
  if (Number(area_dm2) > 0 && Number(amps) >= 0) {
    const cd = Number(amps) / Number(area_dm2);
    actions.push(`Current density terhitung: ${cd.toFixed(2)} A/dm². Bandingkan dengan operating window supplier untuk bath yang benar-benar digunakan.`);
  }
  if (bath === "nickel") {
    if (ph != null && Number.isFinite(Number(ph)) && (Number(ph) < 3 || Number(ph) > 5.5))
      warnings.push("pH berada di luar kisaran kerja umum bath nickel; jangan langsung menambah bahan. Verifikasi metode ukur dan spesifikasi bath.");
    if (temp != null && Number.isFinite(Number(temp)) && (Number(temp) < 40 || Number(temp) > 70))
      warnings.push("Temperatur berada di luar kisaran umum banyak bath nickel; verifikasi spesifikasi supplier.");
    actions.push("Periksa pretreatment, kontak listrik, anoda, filtrasi/agitation dan hasil analisa bath sebelum koreksi.");
  }
  if (missing.length) {
    return { status: "DATA_BELUM_LENGKAP", missing, warnings, actions };
  }
  return { status: warnings.length ? "PERLU_VERIFIKASI" : "PEMERIKSAAN_AWAL", warnings, actions };
}

app.use(express.json({ limit: "1mb" }));
app.use(express.static(path.join(__dirname, "public")));

app.get("/api/health", (_, res) => res.json({ ok: true, ai: Boolean(process.env.GEMINI_API_KEY) }));

app.post("/api/check", (req, res) => {
  const result = localAnalysis(req.body);
  db.prepare(`INSERT INTO bath_checks
    (bath,volume,ph,temp,amps,area_dm2,ni_so4,ni_cl,boric,notes,result)
    VALUES (@bath,@volume,@ph,@temp,@amps,@area_dm2,@ni_so4,@ni_cl,@boric,@notes,@result)`)
    .run({ ...req.body, result: JSON.stringify(result) });
  res.json(result);
});

app.post("/api/chat", async (req, res) => {
  const message = String(req.body.message || "").trim();
  if (!message) return res.status(400).json({ error: "Pertanyaan kosong." });

  let answer;
  if (!process.env.GEMINI_API_KEY) {
    answer = `MODE OFFLINE AKTIF\n\nSaya belum terhubung ke AI eksternal. Saya tetap bisa membantu dengan aturan keselamatan dan pemeriksaan dasar.\n\nPertanyaan Anda: ${message}\n\nUntuk diagnosis yang lebih spesifik, masukkan jenis bak, volume, pH, temperatur, arus, luas aktif, dan hasil analisa chemical.`;
  } else {
    try {
      const ai = new GoogleGenAI({ apiKey: process.env.GEMINI_API_KEY });
      const systemInstruction = `Anda adalah PLATING AI, asisten teknis untuk proses finishing nikel/chrome.
Jawab dalam Bahasa Indonesia, singkat namun operasional.

PENTING: Gunakan jarak spasi ganda (spasi antar paragraf / enter dua kali) di setiap pemisahan baris, daftar poin, dan sub-judul agar teks tidak dempet dan mudah dibaca.

${knowledge}
ATURAN KERAS:
- Jangan mengarang angka target atau dosis chemical.
- Untuk dosis, minta data analisa, volume, assay/konsentrasi produk dan formula supplier.
- Untuk Cr(VI), prioritaskan keselamatan dan jangan memberi instruksi yang meningkatkan paparan.
- Bedakan "data diketahui", "dugaan", dan "tindakan yang disarankan".
- Jika data tidak cukup, ajukan pertanyaan paling penting terlebih dahulu.`;

      const response = await ai.models.generateContent({
        model: process.env.GEMINI_MODEL || "gemini-3.5-flash",
        contents: message,
        config: {
          systemInstruction: systemInstruction,
        }
      });
      answer = response.text;
    } catch (e) {
      answer = `AI ERROR: ${e.message}\n\nMode aturan lokal tetap tersedia melalui menu Cek Bak.`;
    }
  }
  db.prepare("INSERT INTO chats(role,content) VALUES (?,?)").run("user", message);
  db.prepare("INSERT INTO chats(role,content) VALUES (?,?)").run("assistant", answer);
  res.json({ answer });
});

app.get("/api/history", (_, res) => {
  const rows = db.prepare("SELECT * FROM bath_checks ORDER BY id DESC LIMIT 50").all();
  res.json(rows);
});

app.listen(port, () => console.log(`PLATING AI running at http://localhost:${port}`));